name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest
    environment: prod
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Maven
      run: mvn install
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag phqtri/spring-boot:$GITHUB_RUN_NUMBER
    - name: Docker login
      env:
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      run: docker login -u pqtri -p $DOCKER_TOKEN
    - name: Docker push
      run: docker push phqtri/spring-boot:$GITHUB_RUN_NUMBER
